import matplotlib.pyplot as plt
import networkx as nx

G = nx.Graph()
G.add_edge('Valentina', 'Paratibe', weight='5')
G.add_edge('Valentina', 'Mucumagro', weight='4')
G.add_edge('Valentina', 'Colinas do Sul', weight='6')
G.add_edge('Paratibe', 'Valentina', weight='5')
G.add_edge('Paratibe', 'Ernesto Geisel', weight='7')
G.add_edge('Paratibe', 'Gramame', weight='3')
G.add_edge('Paratibe', 'Cristo', weight='9')
G.add_edge('Paratibe', 'Bayeux', weight='10')
G.add_edge('Mucumagro', 'Valentina', weight='4')
G.add_edge('Mucumagro', 'Gramame', weight='2')
G.add_edge('Mucumagro', 'Mangabeira', weight='8')
G.add_edge('Colinas do Sul', 'Valentina', weight='6')
G.add_edge('Colinas do Sul', 'Ernesto Geisel', weight='3')
G.add_edge('Colinas do Sul', 'Mangabeira', weight='5')
G.add_edge('Ernesto Geisel', 'Paratibe', weight='7')
G.add_edge('Ernesto Geisel', 'Colinas do Sul', weight='3')
G.add_edge('Ernesto Geisel', 'Mangabeira', weight='4')
G.add_edge('Ernesto Geisel', 'Cristo', weight='6')
G.add_edge('Ernesto Geisel', 'Tambau', weight='10')
G.add_edge('Mangabeira', 'Mucumagro', weight='8')
G.add_edge('Mangabeira', 'Colinas do Sul', weight='5')
G.add_edge('Mangabeira', 'Ernesto Geisel', weight='4')
G.add_edge('Mangabeira', 'Tambau', weight='9')
G.add_edge('Mangabeira', 'Gramame', weight='6')
G.add_edge('Gramame', 'Paratibe', weight='3')
G.add_edge('Gramame', 'Mucumagro', weight='2')
G.add_edge('Gramame', 'Mangabeira', weight='6')
G.add_edge('Gramame', 'Cristo', weight='6')
G.add_edge('Bayeux', 'Cristo', weight='7')
G.add_edge('Bayeux', 'Paratibe', weight='10')
G.add_edge('Bayeux', 'Santa Rita', weight='5')
G.add_edge('Santa Rita', 'Bayeux', weight='5')
G.add_edge('Santa Rita', 'Tambau', weight='18')
G.add_edge('Tambau', 'Ernesto Geisel', weight='10')
G.add_edge('Tambau', 'Mangabeira', weight='9')
G.add_edge('Tambau', 'Bessa', weight='4')
G.add_edge('Tambau', 'Santa Rita', weight='18')
G.add_edge('Bessa', 'Tambau', weight='4')
G.add_edge('Bessa', 'Mangabeira', weight='18')

pos = nx.spring_layout(G, k=.8,seed=200)  
nx.draw_networkx_nodes(G, pos, node_size=3000, node_color='#e1e8f2', edgecolors='black')
nx.draw_networkx_edges(G, pos, width=2, alpha=0.5, edge_color='gray', style='dashed')
nx.draw_networkx_labels(G, pos, font_size=9, font_family='sans-serif')
edge_labels = nx.get_edge_attributes(G, 'weight')
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_color='red', font_size=9)
plt.title('Mapa de Bairros')
plt.axis('off')
plt.show()
